### PR TITLE
Added unit tests

### PR DESCRIPTION
**Pull request by przygienda**

### CODE REVIEW

**Review by dpc — APPROVED** [review]

**Comment by dpc** [comment]
@przygienda LGTM. I've added you to admins of this repo and crates.io package. Feel free to merge. I and release at your convenience. Thanks!

**Comment by przygienda** [comment]
doesn't seem I can merge the pull request ...

**Comment by dpc** [comment]
"Awaiting przygienda's response" - you have to accept the invite or something.

**Comment by przygienda** [comment]
no bleeping clue where that's supposed to be. nothing in my mailbox ...

**Comment by dpc** [comment]
Oh, I can send you the link directly too: https://github.com/slog-rs/kvfilter/invitations

**Pull request merged**
